### ISSUE TITLE
[PersistentStorage.FileSystem] Unstable tests

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#1089]
# Issue with PersistentStorage.FileSystem

Tests are unstable on net7.0

```
Failed OpenTelemetry.PersistentStorage.FileSystem.Tests.FileBlobProviderTests.FileBlobProvider_CreateBlobReturnsNullIfblobProviderIsFull [8 ms]
  Error Message:
   Assert.False() Failure
Expected: False
Actual:   True
  Stack Trace:
     at OpenTelemetry.PersistentStorage.FileSystem.Tests.FileBlobProviderTests.FileBlobProvider_CreateBlobReturnsNullIfblobProviderIsFull() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.PersistentStorage.FileSystem.Tests\FileBlobProviderTests.cs:line 63
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/4439675079/jobs/7792469052
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/4440203710/jobs/7793712657
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/4439876245/jobs/7792935421

**Comment by Kielek** [comment]
@vishweshbankwar, could you please check?
