### ISSUE TITLE
Flaky unit test on net462

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet-contrib#1325]
`OutgoingRequestInstrumentationTest` has started to fail intermittently. Here is a sample run: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/5979042339/job/16223132226?pr=1322

```cmd
Failed OpenTelemetry.Instrumentation.Wcf.Tests.TelemetryBindingElementForHttpTests.OutgoingRequestInstrumentationTest(instrument: True, filter: False, suppressDownstreamInstrumentation: False, includeVersion: False, enrich: False, enrichmentException: False, emptyOrNullAction: False) [68 ms]
  Error Message:
   Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "DownstreamInstrumentation"
Actual:   "OpenTelemetry.Instrumentation.Wcf.Outgoin"···
           ↑ (pos 0)
  Stack Trace:
     at OpenTelemetry.Instrumentation.Wcf.Tests.TelemetryBindingElementForHttpTests.<OutgoingRequestInstrumentationTest>d__5.MoveNext() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.Wcf.Tests\TelemetryBindingElementForHttpTests.cs:line 258
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by utpilla** [comment]
@repl-chris This has started to occur quite recently. Could any of the changes made in #1247 be causing this?

**Comment by repl-chris** [comment]
Yes, this will absolutely be caused by 1247.  I will try to take a look at it.
