### ISSUE TITLE
BeginConnect must be called on a thread that won't exit

### ISSUE THREAD

**Issue by cataggar** [open-telemetry/opentelemetry-dotnet-contrib#1385]
# Issue with OpenTelemetry.Exporter.Geneva

- OpenTelemetry.Exporter.Geneva 1.6.0
- Azure.Monitor.OpenTelemetry.Exporter 1.0.0
- OpenTelemetry 1.6.0
- OpenTelemetry.Exporter.InMemory 1.6.0
- OpenTelemetry.Instrumentation.Http 1.5.1-beta.1

Runtime version: net6.0

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

No errors in the container logs

**What is the actual behavior?**

A ton of SocketExceptions in the container logs like:

```
Invalid Operation on Socket. Try to recreate socket System.InvalidOperationException: Once the socket has been disconnected, you can only reconnect again asynchronously, and only to a different EndPoint.  BeginConnect must be called on a thread that won't exit until the operation has been completed.
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Microsoft.GenevaAgent.OneDSUnixSocketLogger.LogInformationalEvent(Byte[] message, Int32 length, Boolean queue)
Socket excpetion while connectSystem.Net.Internals.SocketExceptionFactory+ExtendedSocketException (106): Transport endpoint is already connected /var/run/mdsd/default_fluent.socket
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Microsoft.GenevaAgent.OneDSUnixSocketLogger.LogInformationalEvent(Byte[] message, Int32 length, Boolean queue)
Socket excpetion while connectSystem.Net.Sockets.SocketException (32): Broken pipe
   at Microsoft.GenevaAgent.OneDSUnixSocketLogger.LogInformationalEvent(Byte[] message, Int32 length, Boolean queue)
```

## Additional Context

I get the errors with OpenTelemetry.Exporter.Geneva 1.4.1 and 1.6.0. Both versions that I've tried. The telemetry is showing up in DGrep.

**Comment by cataggar** [comment]
I see, this error is thrown from GenevaAgent. We would like to continue to run too while we transition off of it. Is there a way to have both run without these errors? Both are using the default socket of  `/var/run/mdsd/default_fluent.socket`.

**Comment by cataggar** [comment]
This is currently happening with just the GenevaAgent. I look forward to retiring GenevaAgent.
