### ISSUE TITLE
NotSupportedException: Services cannot be configured after ServiceProvider has been created.

### ISSUE THREAD

**Issue by bbwang13** [open-telemetry/opentelemetry-dotnet-contrib#1495]
# Bug Report

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry.Exporter.Geneva 1.6.0
* net8.0

## Symptom

I used `AddOpenTelemetry().WithMetrics()` to add metrics and set Geneva exporting options specifying the Geneva account and namespace. Build passed but throw exceptions at runtime.

**What is the expected behavior?**

No exceptions.

What did you expect to see?

No exceptions and metrics can be uploaded to Geneva backend.

What did you see instead?

```
Unhandled exception. System.NotSupportedException: Services cannot be configured after ServiceProvider has been created.
   at OpenTelemetry.Metrics.MeterProviderBuilderSdk.ConfigureServices(Action`1 configure)
   at OpenTelemetry.Metrics.OpenTelemetryDependencyInjectionMeterProviderBuilderExtensions.ConfigureServices(MeterProviderBuilder meterProviderBuilder, Action`1 configure)
   at OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.AddGenevaMetricExporter(MeterProviderBuilder builder, String name, Action`1 configure)
   at OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.AddGenevaMetricExporter(MeterProviderBuilder builder, Action`1 configure)
   at Microsoft.R9.Extensions.Metering.Exporters.GenevaMeteringExporterExtensions.AddGenevaExporter(MeterProviderBuilder builder, IEnumerable`1 enrichers, GenevaMeteringExporterOptions options, Action`1 configure)
   at Microsoft.R9.Extensions.Metering.Exporters.GenevaMeteringExporterExtensions.<>c__DisplayClass2_0.<AddGenevaExporter>b__1(IServiceProvider sp, MeterProviderBuilder meterProviderBuilder)
   at OpenTelemetry.Metrics.OpenTelemetryDependencyInjectionMetricsServiceCollectionExtensions.ConfigureMeterProviderBuilderCallbackWrapper.ConfigureBuilder(IServiceProvider serviceProvider, MeterProviderBuilder meterProviderBuilder)
   at OpenTelemetry.Metrics.MeterProviderSdk..ctor(IServiceProvider serviceProvider, Boolean ownsServiceProvider)
   at OpenTelemetry.Metrics.MeterProviderBuilderBase.<>c.<.ctor>b__3_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService.Initialize(IServiceProvider serviceProvider)
   at OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
```

## Reproduce

The code at the DI part like:
```C#
                    services.AddOpenTelemetry().WithMetrics(builder =>
                    {
                        var config = context.Configuration.GetSection("Metrics");
                        builder.AddMetering()
                            .AddView((instrument) =>
                            {
                                if (instrument.GetType().Name.Contains("Histogram"))
                                {
                                    return new Base2ExponentialBucketHistogramConfiguration();
                                }

                                return null;
                            })
                            .AddGenevaExporter(options =>
                            {
                                options.MonitoringAccount = "A";
                                options.MonitoringNamespace = "B";
                            });
                    });

```

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

I tried to add `GenevaMetringOptions` outside the `OpenTelemetry` part, no exceptions, but the metrics still cannot upload:

```C#
                    services.Configure<GenevaMeteringOptions>(options =>
                    {
                        options.MonitoringAccount = "A";
                        options.MonitoringNamespace = "B";
                    });
```

**Comment by cijothomas** [comment]
@CodeBlanch cna you help

**Comment by CodeBlanch** [comment]
@bbwang13 It looks like the exception is being thrown out of `Microsoft.R9.Extensions.Metering`:

```
   at Microsoft.R9.Extensions.Metering.Exporters.GenevaMeteringExporterExtensions.AddGenevaExporter(MeterProviderBuilder builder, IEnumerable`1 enrichers, GenevaMeteringExporterOptions options, Action`1 configure)
   at Microsoft.R9.Extensions.Metering.Exporters.GenevaMeteringExporterExtensions.<>c__DisplayClass2_0.<AddGenevaExporter>b__1(IServiceProvider sp, MeterProviderBuilder meterProviderBuilder)
```

What version of `Microsoft.R9.Extensions.Metering` are you using? This isn't something we support but I'll try to provide some guidance on what you can do or connect you to the correct people to help.

**Comment by kerryjiang** [comment]
The stacktrace:
at OpenTelemetry.Metrics.MeterProviderBuilderSdk.ConfigureServices(Action`1 configure) in OpenTelemetry.Metrics\MeterProviderBuilderSdk.cs:line 170
   at OpenTelemetry.Metrics.OpenTelemetryDependencyInjectionMeterProviderBuilderExtensions.ConfigureServices(MeterProviderBuilder meterProviderBuilder, Action`1 configure) in OpenTelemetry.Metrics\OpenTelemetryDependencyInjectionMeterProviderBuilderExtensions.cs:line 68
   at OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.AddGenevaMetricExporter(MeterProviderBuilder builder, String name, Action`1 configure)
   at OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.AddGenevaMetricExporter(MeterProviderBuilder builder, Action`1 configure)

**Comment by kerryjiang** [comment]
OpenTelemetry.Exporter.Geneva 1.6.0
dotnet8


Same code works when we use OpenTelemetry.Exporter.Geneva 1.4.0 + dotnet 7

**Comment by alexaloni** [comment]
Same issue occurs with 1.7.0 on .net 8 
![image](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/assets/18429331/80f76bad-90d8-4ba0-9352-a9b1d83084ad)

**Comment by CodeBlanch** [comment]
There's a bit to unpack here 🤣

GenevaExporter gained support for the Microsoft.Extensions.Options API here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1218

If you pass some configuration delegate to `AddGeneva[Trace|Metric]Exporter(options => { /* do configuration*/ })` it will get registered into the `IServiceCollection` ([example here](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/b73db3014964b4173a71b342dbc38923fadbe2fb/src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporterExtensions.cs#L46)).

This will work fine:

```csharp
builder.Services.AddOpenTelemetry().WithMetrics(builder => builder.AddGenevaMetricExporter(configureOptions))
```

This will throw:

```csharp
builder.Services.ConfigureOpenTelemetryMeterProvider((serviceProvider, builder) =>
{
    // IServiceProvider has been created, services can no longer be added.

    builder.AddGenevaMetricExporter(configureOptions); // Attempts to add a service for configureOptions, throws
});
```

I just updated the README to show how to do it correctly: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Geneva/README.md#how-to-configure-genevametricexporteroptions-using-dependency-injection

Essentially the fix is to just embrace the Options API to accomplish the goal.

**Comment by CodeBlanch** [comment]
I'm going to close this but feel free to reopen or continue the conversation.
