### ISSUE TITLE
[bug] OpenTelemetry.Exporter.Geneva v1.9.0 is incompatible with OpenTelemetry.Exporter.OpenTelemetryProtocol v1.10.0 on Windows

### ISSUE THREAD

**Issue by pedropaulovc** [open-telemetry/opentelemetry-dotnet-contrib#2331]
### Component

OpenTelemetry.Exporter.Geneva

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry.Exporter.Geneva                     | 1.9.0   |
| OpenTelemetry.Exporter.OpenTelemetryProtocol | 1.10.0   |
| OpenTelemetry.Extensions.Hosting                                   | 1.10.0 |

### Runtime Version

net9.0

### Description

There are API breaking changes in `OpenTelemetry.Exporter.OpenTelemetryProtocol` that cause `OpenTelemetry.Exporter.Geneva` v1.9.0 to be incompatible with `OpenTelemetry.Exporter.OpenTelemetryProtocol` v1.10.0. Users must downgrade to v1.9.0 to mitigate this issue.

A new version of `OpenTelemetry.Exporter.Geneva` should be released to account for the new API changes.

### Steps to Reproduce

Execute `dotnet run` on the project below on Windows:

**Project.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Geneva" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.10.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.10.0" />
  </ItemGroup>

</Project>
```

**Program.cs**
```cs
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using OpenTelemetry.Exporter.Geneva;
using OpenTelemetry.Logs;
using Microsoft.Extensions.Logging;

var builder = new HostApplicationBuilder();

builder.Services
    .AddOpenTelemetry()
    .WithLogging(logging =>
    {
        logging.AddGenevaLogExporter(options =>
        {
            options.ConnectionString = "EtwSession=OpenTelemetry";
        });
    });

var serviceProvider = builder.Services.BuildServiceProvider();

serviceProvider.GetService<LoggerProvider>();
```

### Expected Result

The executable runs successfully.

### Actual Result

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenTelemetry.Exporter.Geneva.ReentrantExportProcessor`1' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'constructor')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at OpenTelemetry.Exporter.Geneva.ReentrantExportProcessor`1..cctor()
   --- End of inner exception stack trace ---
   at OpenTelemetry.Exporter.Geneva.ReentrantExportProcessor`1..ctor(BaseExporter`1 exporter)
   at Microsoft.Extensions.Logging.GenevaLoggingExtensions.BuildGenevaLogExporter(BatchExportLogRecordProcessorOptions batchExportLogRecordProcessorOptions, GenevaExporterOptions exporterOptions)
   at Microsoft.Extensions.Logging.GenevaLoggingExtensions.<>c__DisplayClass3_0.<AddGenevaLogExporter>b__1(IServiceProvider sp)
   at OpenTelemetry.Logs.LoggerProviderBuilderExtensions.<>c__DisplayClass4_0.<AddProcessor>b__0(IServiceProvider sp, LoggerProviderBuilder builder)
   at OpenTelemetry.Logs.OpenTelemetryDependencyInjectionLoggingServiceCollectionExtensions.ConfigureLoggerProviderBuilderCallbackWrapper.ConfigureBuilder(IServiceProvider serviceProvider, LoggerProviderBuilder loggerProviderBuilder)
   at OpenTelemetry.Logs.LoggerProviderSdk..ctor(IServiceProvider serviceProvider, Boolean ownsServiceProvider)
   at OpenTelemetry.Logs.LoggerProviderBuilderBase.<>c.<.ctor>b__3_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Program.<Main>$(String[] args) in C:\src\TMP\OtelGenevaVersionBug\Program.cs:line 21
```

**Comment by rajkumar-rangaraj** [comment]
Could you please test with OpenTelemetry.Exporter.Geneva version 1.10.0 and check if the issue is resolved?

**Comment by pedropaulovc** [comment]
Confirmed that version 1.10.0 resolves the issue. Thanks!
