### ISSUE TITLE
Instrumentation is nor working with MySql.Data 8.0.31

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#691]
# Issue with OpenTelemetry.Instrumentation.MySqlData

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using:

* https://www.nuget.org/packages/OpenTelemetry.Instrumentation.MySqlData/1.0.0-beta.3
* https://www.nuget.org/packages/MySql.Data/8.0.31

Other are non-important.

Runtime version:

net6.0 and other

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

Spans are correctly recorded by the package.
It will be great to have one package version which support both pre 8.0.31 and 8.0.31+ as we are using it on the OTel .NET AutoInstrumentation.

**What is the actual behavior?**

Log from OpenTelemetry .NET Auto Instrumentation 
```log
'MySqlDataInitializer' failed 
Exception: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Void MySql.Data.MySqlClient.MySqlTrace.set_QueryAnalysisEnabled(Boolean)'.
   at OpenTelemetry.Instrumentation.MySqlData.MySqlDataInstrumentation..ctor(MySqlDataInstrumentationOptions options)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at OpenTelemetry.AutoInstrumentation.Loading.MySqlDataInitializer.Initialize(ILifespanManager lifespanManager) in C:\GitHub\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation\Loading\MySqlDataInitializer.cs:line 32
   at OpenTelemetry.AutoInstrumentation.Loading.LazyInstrumentationLoader.OnAssemblyLoadInitializer.CurrentDomain_AssemblyLoad(Object sender, AssemblyLoadEventArgs args) in C:\GitHub\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation\Loading\LazyInstrumentationLoader.cs:line 70
```

## Additional Context

Issue caused by https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/7fb378deb11143891b4b944a4e5497b376c2899a/src/OpenTelemetry.Instrumentation.MySqlData/MySqlDataInstrumentation.cs#L40 and the breaking change in this commit: API removal: https://github.com/mysql/mysql-connector-net/commit/61fdbe5f0967b90a9f93e8d280d28d2effe7f7a8

Needed by: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1415

**Comment by Kielek** [comment]
@moonheart, FYI as you are component owner.

**Comment by Kielek** [comment]
I am not sure if adding Logging or UseUsageAdvisor is the best option (probably only possible right now).
Both this options cause some side effects (additional operations are executed when any of them is enabled:
See https://github.com/mysql/mysql-connector-net/blob/3ebd5c49432a7bcff96438a7f9b193576acda30a/MySQL.Data/src/ProcedureCache.cs#L73-L80 or 
https://github.com/mysql/mysql-connector-net/blob/3ebd5c49432a7bcff96438a7f9b193576acda30a/MySQL.Data/src/TracingDriver.cs#L204

Do you think that it is worth to report it to Oracle to bring the functionality (off course without any reference to EMTrace)?

Notes: Tracer driver is enabled when: https://github.com/mysql/mysql-connector-net/blob/61fdbe5f0967b90a9f93e8d280d28d2effe7f7a8/MySQL.Data/src/Driver.cs#L141-L143

**Comment by moonheart** [comment]
Yes, there are two properties `Logging` and `UseUsageAdvisor` that we can use to enable the `TracingDriver`.
According to the Mysql documentation [here](https://dev.mysql.com/doc/connector-net/en/connector-net-8-0-connection-options.html), `Logging` is more appropriate for tracing purpose, while `UseUsageAdvisor` is used to log inefficient database operations.
