### ISSUE TITLE
FlakyTests

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet-contrib#716]
Flaky test:

[xUnit.net 00:00:02.01]     OpenTelemetry.Instrumentation.AspNet.Tests.HttpInListenerTests.AspNetRequestsAreCollectedSuccessfully(expectedUrl: "http://localhost/api/value", url: "http://localhost/api/value", routeType: 0, routeTemplate: null, setStatusToErrorInEnrich: False, filter: "{ThrowException}", recordException: False) [FAIL]
  Failed OpenTelemetry.Instrumentation.AspNet.Tests.HttpInListenerTests.AspNetRequestsAreCollectedSuccessfully(expectedUrl: "http://localhost/api/value", url: "http://localhost/api/value", routeType: 0, routeTemplate: null, setStatusToErrorInEnrich: False, filter: "{ThrowException}", recordException: False) [52 ms]
  Error Message:
   The collection was expected to contain a single element, but it contained 2 elements.
  Stack Trace:
     at OpenTelemetry.Instrumentation.AspNet.Tests.HttpInListenerTests.AspNetRequestsAreCollectedSuccessfully(String expectedUrl, String url, Int32 routeType, String routeTemplate, Boolean setStatusToErrorInEnrich, String filter, Boolean recordException) in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.AspNet.Tests\HttpInListenerTests.cs:line 153

**Comment by cijothomas** [comment]
[xUnit.net 00:00:01.92]     OpenTelemetry.Instrumentation.AspNet.Tests.HttpInMetricsListenerTests.HttpDurationMetricIsEmitted [FAIL]
  Failed OpenTelemetry.Instrumentation.AspNet.Tests.HttpInMetricsListenerTests.HttpDurationMetricIsEmitted [315 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 7.8940000000000001
Actual:   11.745800000000001
  Stack Trace:
     at OpenTelemetry.Instrumentation.AspNet.Tests.HttpInMetricsListenerTests.HttpDurationMetricIsEmitted() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.AspNet.Tests\HttpInMetricsListenerTests.cs:line 79

Attachments:
  D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\TestResults\34f83e71-ccc4-423f-a965-0f6c2c6aeb45\runneradmin_fv-az269-594_2022-10-21.09_37_32.coverage
Failed!  - Failed:     1, Passed:    21, Skipped:     0, Total:    22, Duration: 422 ms - OpenTelemetry.Instrumentation.AspNet.Tests.dll (net462)

**Comment by cijothomas** [comment]
A total of 1 test files matched the specified pattern.
  Failed OpenTelemetry.Instrumentation.Hangfire.Tests.HangfireInstrumentationJobFilterAttributeTests.Should_Create_Activity_With_Status_Error_When_Job_Failed [322 ms]
  Error Message:
   System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
  Stack Trace:
     at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenTelemetry.Instrumentation.Hangfire.Tests.HangfireInstrumentationJobFilterAttributeTests.<WaitJobProcessedAsync>d__6.MoveNext() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.Hangfire.Tests\HangfireInstrumentationJobFilterAttributeTests.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OpenTelemetry.Instrumentation.Hangfire.Tests.HangfireInstrumentationJobFilterAttributeTests.<Should_Create_Activity_With_Status_Error_When_Job_Failed>d__3.MoveNext() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.Hangfire.Tests\HangfireInstrumentationJobFilterAttributeTests.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by Oberon00** [comment]
From CI run for https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1270/commits/5acd530f70fade01104776f39b000820615560f0:

```
2023-07-18T15:36:33.5008155Z [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.9)
2023-07-18T15:36:34.0200913Z [xUnit.net 00:00:00.53]   Discovering: OpenTelemetry.Instrumentation.Hangfire.Tests
2023-07-18T15:36:34.0589441Z [xUnit.net 00:00:00.57]   Discovered:  OpenTelemetry.Instrumentation.Hangfire.Tests
2023-07-18T15:36:34.0624229Z [xUnit.net 00:00:00.57]   Starting:    OpenTelemetry.Instrumentation.Hangfire.Tests
2023-07-18T15:36:34.5551443Z [xUnit.net 00:00:01.05]     OpenTelemetry.Instrumentation.Hangfire.Tests.HangfireInstrumentationJobFilterAttributeTests.Should_Create_Activity_With_Status_Error_When_Job_Failed [FAIL]
2023-07-18T15:36:34.5552699Z [xUnit.net 00:00:01.05]       System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
2023-07-18T15:36:34.5554807Z [xUnit.net 00:00:01.05]       Stack Trace:
2023-07-18T15:36:34.5555773Z [xUnit.net 00:00:01.05]            at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
2023-07-18T15:36:34.5556693Z [xUnit.net 00:00:01.05]            at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
2023-07-18T15:36:34.5559627Z [xUnit.net 00:00:01.05]         D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.Hangfire.Tests\HangfireInstrumentationJobFilterAttributeTests.cs(157,0): at OpenTelemetry.Instrumentation.Hangfire.Tests.HangfireInstrumentationJobFilterAttributeTests.WaitJobProcessedAsync(String jobId, Int32 timeToWaitInSeconds)
2023-07-18T15:36:34.5563935Z [xUnit.net 00:00:01.05]         D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.Hangfire.Tests\HangfireInstrumentationJobFilterAttributeTests.cs(71,0): at OpenTelemetry.Instrumentation.Hangfire.Tests.HangfireInstrumentationJobFilterAttributeTests.Should_Create_Activity_With_Status_Error_When_Job_Failed()
2023-07-18T15:36:34.5566329Z [xUnit.net 00:00:01.05]         --- End of stack trace from previous location ---
2023-07-18T15:36:34.9320774Z   Failed OpenTelemetry.Instrumentation.Hangfire.Tests.HangfireInstrumentationJobFilterAttributeTests.Should_Create_Activity_With_Status_Error_When_Job_Failed [303 ms]
2023-07-18T15:36:34.9322116Z   Error Message:
2023-07-18T15:36:34.9322588Z    System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
2023-07-18T15:36:34.9322995Z   Stack Trace:
2023-07-18T15:36:34.9323391Z      at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
2023-07-18T15:36:34.9323923Z    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
2023-07-18T15:36:34.9326378Z    at OpenTelemetry.Instrumentation.Hangfire.Tests.HangfireInstrumentationJobFilterAttributeTests.WaitJobProcessedAsync(String jobId, Int32 timeToWaitInSeconds) in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.Hangfire.Tests\HangfireInstrumentationJobFilterAttributeTests.cs:line 157
2023-07-18T15:36:34.9329362Z    at OpenTelemetry.Instrumentation.Hangfire.Tests.HangfireInstrumentationJobFilterAttributeTests.Should_Create_Activity_With_Status_Error_When_Job_Failed() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.Hangfire.Tests\HangfireInstrumentationJobFilterAttributeTests.cs:line 71
2023-07-18T15:36:34.9330839Z --- End of stack trace from previous location ---
2023-07-18T15:36:38.1045980Z [xUnit.net 00:00:04.61]   Finished:    OpenTelemetry.Instrumentation.Hangfire.Tests
```
