### ISSUE TITLE
[Extensions.AzureMonitor] ApplicationInsightsSamplerTests.VerifyHashAlgorithmCorrectness is failing

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#891]
# Issue with OpenTelemetry.Extensions.AzureMonitor

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* Current main branch.

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* `net6.0`, `net7.0`

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

Tests Passed.

**What is the actual behavior?**

Following tests is continuously failing.

```[xUnit.net 00:00:01.20]     OpenTelemetry.Extensions.AzureMonitor.Tests.ApplicationInsightsSamplerTests.VerifyHashAlgorithmCorrectness [FAIL]
  Failed OpenTelemetry.Extensions.AzureMonitor.Tests.ApplicationInsightsSamplerTests.VerifyHashAlgorithmCorrectness [11 ms]
  Error Message:
   Assert.Equal() Failure
Expected: Drop
Actual:   RecordAndSample
  Stack Trace:
     at OpenTelemetry.Extensions.AzureMonitor.Tests.ApplicationInsightsSamplerTests.VerifyHashAlgorithmCorrectness() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Extensions.AzureMonitor.Tests\ApplicationInsightsSamplerTests.cs:line 62
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Notes**
Previously tests was not executed in pipeline. It is fixed in #890

**Comment by Kielek** [comment]
@rajkumar-rangaraj, @vishweshbankwar, could you please check?

**Comment by TimothyMothra** [comment]
I tried to take a look at this, but the tests won't run for me.

```
dotnet test

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in C:\REPOS\opentelemetry-dotnet-contrib-fork\test\OpenTelemetry.Extensions.AzureMonitor.Tests\bin\Debug\net7.0\OpenTelemetry.Extensions.AzureMonitor.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

**Comment by TimothyMothra** [comment]
I have a fix.
The test is evaluating two TraceIds, and asserting that for a given sampling ratio, one should be dropped and the other should be sampled. It seems that sampling ratio is too high. 

I'll take some more time to review if something changed. 

I should have a PR by EOD :)

**Comment by TimothyMothra** [comment]
Found what changed.

#846
`TraceId.ToHexString().ToLowerInvariant()` was changed to `TraceId.ToHexString().ToUpperInvariant()`

This changed the computed sampling score. This would have been caught if the tests were correctly running in CI.
