### ISSUE TITLE
Flaky test again

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet-contrib#910]
[xUnit.net 00:00:02.23]     OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.EventCounter [FAIL]
[xUnit.net 00:00:02.23]       Assert.Equal() Failure
[xUnit.net 00:00:02.23]       Expected: 1997.0201999999999
[xUnit.net 00:00:02.23]       Actual:   0
[xUnit.net 00:00:02.23]       Stack Trace:
[xUnit.net 00:00:02.23]         D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.EventCounters.Tests\EventCountersMetricsTests.cs(74,0): at OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.EventCounter()
  Failed OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.EventCounter [1 s]
  Error Message:
   Assert.Equal() Failure
Expected: 1997.0201999999999
Actual:   0
  Stack Trace:
     at OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.EventCounter() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.EventCounters.Tests\EventCountersMetricsTests.cs:line 74

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/3958515715

**Comment by martinjt** [comment]
Looks like this was merged and fixed.

**Comment by cijothomas** [comment]
> Looks like this was merged and fixed.

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs#L17 The tests are still ignored, not fixed.

**Comment by martinjt** [comment]
Assigned to the maintainers of the event counters library.

**Comment by martincostello** [comment]
This was resolved in #3369.
