### ISSUE TITLE
Histogram with negative values

### ISSUE THREAD

**Issue by aelij** [open-telemetry/opentelemetry-dotnet-contrib#912]
# Issue with OpenTelemetry.Exporter.Geneva

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 1.0.2`):
* OpenTelemetry, 1.4.0-rc.2
* OpenTelemetry.Exporter.Geneva, 1.4.0-rc.1

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can find this information from the `*.csproj` file):
* net7.0

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**
Allow negative values in histograms

**What is the actual behavior?**

```cs
var m = new Meter("m");
var h = m.CreateHistogram<long>("h");
h.Record(-1);
```

Exception:
```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Convert.ToUInt64(Double value)
   at OpenTelemetry.Exporter.Geneva.GenevaMetricExporter.Export(Batch`1& batch)
```

## Additional Context

Add any other context about the feature request here.

**Comment by Dytroxx** [comment]
Hello, I’m interested in contributing and would like to take on this issue if possible.
Please let me know if it’s okay for me to proceed. Thank you.

**Comment by martincostello** [comment]
@rajkumar-rangaraj If we don't want to implement this issue in Geneva should we close this issue so others don't try to pick it up?
