### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet-contrib#941]
OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.PollingCounter()
  Failed OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.PollingCounter [1 s]
  Error Message:
   Assert.Equal() Failure
Expected: 10
Actual:   20
  Stack Trace:
     at OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.PollingCounter() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.EventCounters.Tests\EventCountersMetricsTests.cs:line 107

**Comment by reyang** [comment]
@mic-max would you take a look?

**Comment by cijothomas** [comment]
[xUnit.net 00:00:09.75]     OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.PollingCounter [FAIL]
[xUnit.net 00:00:09.75]       Assert.Equal() Failure
[xUnit.net 00:00:09.75]       Expected: 10
[xUnit.net 00:00:09.75]       Actual:   20
[xUnit.net 00:00:09.75]       Stack Trace:
[xUnit.net 00:00:09.75]         /home/runner/work/opentelemetry-dotnet-contrib/opentelemetry-dotnet-contrib/test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs([107](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/4184402706/jobs/7255148867#step:7:108),0): at OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.PollingCounter()
  Failed OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.PollingCounter [1 s]
  Error Message:
   Assert.Equal() Failure
Expected: 10
Actual:   20
  Stack Trace:
     at OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.PollingCounter() in /home/runner/work/opentelemetry-dotnet-contrib/opentelemetry-dotnet-contrib/test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs:line 107
[xUnit.net 00:00:11.76]     OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.IncrementingPollingCounter [FAIL]
[xUnit.net 00:00:11.76]       Assert.Equal() Failure
[xUnit.net 00:00:11.76]       Expected: 1
[xUnit.net 00:00:11.76]       Actual:   2
[xUnit.net 00:00:11.76]       Stack Trace:
[xUnit.net 00:00:11.76]         /home/runner/work/opentelemetry-dotnet-contrib/opentelemetry-dotnet-contrib/test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs(133,0): at OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.IncrementingPollingCounter()
[xUnit.net 00:00:11.76]   Finished:    OpenTelemetry.Instrumentation.EventCounters.Tests
  Passed OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.IncrementingEventCounter [1 s]
  Failed OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.IncrementingPollingCounter [1 s]
  Error Message:
   Assert.Equal() Failure
Expected: 1
Actual:   2
  Stack Trace:
     at OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.IncrementingPollingCounter() in /home/runner/work/opentelemetry-dotnet-contrib/opentelemetry-dotnet-contrib/test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs:line 133

**Comment by vishweshbankwar** [comment]
I think the issue is surfacing due to EventCounter callback being called multiple times or not at all (before the asserts). Need to check if we can have a way around this to restrict callback to get called only once for testing purposes. @mic-max FYI

**Comment by martincostello** [comment]
This tests aren't disabled anymore.
