### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet-contrib#977]
[xUnit.net 00:00:00.53]   Starting:    OpenTelemetry.Extensions.Tests
[xUnit.net 00:00:00.86]     OpenTelemetry.Extensions.Tests.Trace.AutoFlushActivityProcessorTests.AutoFlushActivityProcessor_FlushAfterLocalServerSideRootSpans_EndMatchingSpan_Flush [FAIL]
[xUnit.net 00:00:00.86]       Moq.MockException : 
[xUnit.net 00:00:00.86]       Expected invocation on the mock once, but was 2 times: mock => mock.OnForceFlush(5000)
[xUnit.net 00:00:00.86]       
[xUnit.net 00:00:00.86]       Performed invocations:
[xUnit.net 00:00:00.86]       
[xUnit.net 00:00:00.86]          Mock<BaseProcessor<Activity>:1> (mock):
[xUnit.net 00:00:00.86]       
[xUnit.net 00:00:00.86]             BaseProcessor<Activity>.SetParentProvider(TracerProviderSdk)
[xUnit.net 00:00:00.86]             BaseProcessor<Activity>.SetParentProvider(TracerProviderSdk)
[xUnit.net 00:00:00.86]             BaseProcessor<Activity>.OnStart(Activity)
[xUnit.net 00:00:00.86]             BaseProcessor<Activity>.OnStart(Activity)
[xUnit.net 00:00:00.86]             BaseProcessor<Activity>.OnEnd(Activity)
[xUnit.net 00:00:00.86]             BaseProcessor<Activity>.OnForceFlush(5000)
[xUnit.net 00:00:00.86]             BaseProcessor<Activity>.OnEnd(Activity)
[xUnit.net 00:00:00.86]             BaseProcessor<Activity>.OnForceFlush(5000)
[xUnit.net 00:00:00.86]       
[xUnit.net 00:00:00.86]       Stack Trace:
[xUnit.net 00:00:00.86]         C:\projects\moq4\src\Moq\Mock.cs(330,0): at Moq.Mock.Verify(Mock mock, LambdaExpression expression, Times times, String failMessage)
[xUnit.net 00:00:00.86]         C:\projects\moq4\src\Moq\Protected\ProtectedMock.cs([234](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/4118136049/jobs/7110296614#step:7:235),0): at Moq.Protected.ProtectedMock`1.InternalVerify(String methodName, Type[] genericTypeArguments, Times times, Boolean exactParameterMatch, Object[] args)
[xUnit.net 00:00:00.86]         C:\projects\moq4\src\Moq\Protected\ProtectedMock.cs(206,0): at Moq.Protected.ProtectedMock`1.Verify(String methodName, Times times, Object[] args)
[xUnit.net 00:00:00.86]         D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Extensions.Tests\Trace\AutoFlushActivityProcessorTests.cs(45,0): at OpenTelemetry.Extensions.Tests.Trace.AutoFlushActivityProcessorTests.AutoFlushActivityProcessor_FlushAfterLocalServerSideRootSpans_EndMatchingSpan_Flush()

**Comment by cijothomas** [comment]
Failed OpenTelemetry.Extensions.Tests.Trace.AutoFlushActivityProcessorTests.AutoFlushActivityProcessor_FlushAfterLocalServerSideRootSpans_EndMatchingSpan_Flush [151 ms]
  Error Message:
   Moq.MockException : 
Expected invocation on the mock once, but was 2 times: mock => mock.OnForceFlush(5000)

Performed invocations:

   Mock<BaseProcessor<Activity>:1> (mock):

      BaseProcessor<Activity>.SetParentProvider(TracerProviderSdk)
      BaseProcessor<Activity>.SetParentProvider(TracerProviderSdk)
      BaseProcessor<Activity>.OnStart(Activity)
      BaseProcessor<Activity>.OnEnd(Activity)
      BaseProcessor<Activity>.OnForceFlush(5000)
      BaseProcessor<Activity>.OnEnd(Activity)
      BaseProcessor<Activity>.OnForceFlush(5000)

  Stack Trace:
     at Moq.Mock.Verify(Mock mock, LambdaExpression expression, Times times, String failMessage) in C:\projects\moq4\src\Moq\Mock.cs:line 330
   at Moq.Protected.ProtectedMock`1.InternalVerify(String methodName, Type[] genericTypeArguments, Times times, Boolean exactParameterMatch, Object[] args) in C:\projects\moq4\src\Moq\Protected\ProtectedMock.cs:line 234
   at Moq.Protected.ProtectedMock`1.Verify(String methodName, Times times, Object[] args) in C:\projects\moq4\src\Moq\Protected\ProtectedMock.cs:line 206
   at OpenTelemetry.Extensions.Tests.Trace.AutoFlushActivityProcessorTests.AutoFlushActivityProcessor_FlushAfterLocalServerSideRootSpans_EndMatchingSpan_Flush() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Extensions.Tests\Trace\AutoFlushActivityProcessorTests.cs:line 45
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by cijothomas** [comment]
Failed OpenTelemetry.Extensions.Tests.Trace.AutoFlushActivityProcessorTests.AutoFlushActivityProcessor_FlushAfterLocalServerSideRootSpans_EndMatchingSpan_Flush [120 ms]
  Error Message:
   Moq.MockException : 
Expected invocation on the mock once, but was 2 times: mock => mock.OnForceFlush(5000)

Performed invocations:

   Mock<BaseProcessor<Activity>:1> (mock):

      BaseProcessor<Activity>.SetParentProvider(TracerProviderSdk)
      BaseProcessor<Activity>.SetParentProvider(TracerProviderSdk)
      BaseProcessor<Activity>.OnStart(Activity)
      BaseProcessor<Activity>.OnEnd(Activity)
      BaseProcessor<Activity>.OnForceFlush(5000)
      BaseProcessor<Activity>.OnEnd(Activity)
      BaseProcessor<Activity>.OnForceFlush(5000)

  Stack Trace:
     at Moq.Mock.Verify(Mock mock, LambdaExpression expression, Times times, String failMessage) in C:\projects\moq4\src\Moq\Mock.cs:line 330
   at Moq.Protected.ProtectedMock`1.InternalVerify(String methodName, Type[] genericTypeArguments, Times times, Boolean exactParameterMatch, Object[] args) in C:\projects\moq4\src\Moq\Protected\ProtectedMock.cs:line 234
   at Moq.Protected.ProtectedMock`1.Verify(String methodName, Times times, Object[] args) in C:\projects\moq4\src\Moq\Protected\ProtectedMock.cs:line 206
   at OpenTelemetry.Extensions.Tests.Trace.AutoFlushActivityProcessorTests.AutoFlushActivityProcessor_FlushAfterLocalServerSideRootSpans_EndMatchingSpan_Flush() in D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Extensions.Tests\Trace\AutoFlushActivityProcessorTests.cs:line 45
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by martinjt** [comment]
Looks like this was merged and fixed.
